bundles:
- addonChannel: stable
  image: quay.io/acm-d/acm-operator-bundle:v2.6.0-104
  operator: advanced-cluster-management
  version: 2.6.0
- addonChannel: stable
  image: quay.io/acm-d/acm-operator-bundle:v2.6.1-2
  operator: advanced-cluster-management
  version: 2.6.1
- addonChannel: beta
  image: quay.io/acm-d/acm-operator-bundle:v2.5.0-304
  operator: advanced-cluster-management
  version: 2.5.0
- addonChannel: beta
  image: quay.io/acm-d/acm-operator-bundle:v2.5.1-13
  operator: advanced-cluster-management
  version: 2.5.1
- addonChannel: beta
  image: quay.io/acm-d/acm-operator-bundle:v2.5.2-42
  operator: advanced-cluster-management
  version: 2.5.2
- addonChannel: beta
  image: quay.io/acm-d/acm-operator-bundle:v2.6.0-104
  operator: advanced-cluster-management
  version: 2.6.0
- addonChannel: beta
  image: quay.io/acm-d/acm-operator-bundle:v2.6.1-2
  operator: advanced-cluster-management
  version: 2.6.1
- addonChannel: beta
  image: quay.io/acm-d/acm-operator-bundle:v2.7.0-41
  operator: advanced-cluster-management
  version: 2.7.0
- addonChannel: beta
  image: quay.io/acm-d/mce-operator-bundle:v2.0.0-150
  operator: multicluster-engine
  parent: advanced-cluster-management
  version: 2.0.0
- addonChannel: beta
  image: quay.io/acm-d/mce-operator-bundle:v2.0.1-17
  operator: multicluster-engine
  parent: advanced-cluster-management
  version: 2.0.1
- addonChannel: beta
  image: quay.io/acm-d/mce-operator-bundle:v2.0.2-29
  operator: multicluster-engine
  parent: advanced-cluster-management
  version: 2.0.2
- addonChannel: beta
  image: quay.io/acm-d/mce-operator-bundle:v2.2.0-59
  operator: multicluster-engine
  parent: advanced-cluster-management
  version: 2.2.0
- addonChannel: beta
  image: quay.io/acm-d/mce-operator-bundle:v2.1.0-123
  operator: multicluster-engine
  parent: advanced-cluster-management
  version: 2.1.0
- addonChannel: beta
  image: quay.io/acm-d/mce-operator-bundle:v2.1.1-5
  operator: multicluster-engine
  parent: advanced-cluster-management
  version: 2.1.1
- addonChannel: beta
  csvNameOverride: klusterlet-product
  image: quay.io/acm-d/klusterlet-operator-bundle:v2.0.0-110
  operator: klusterlet-operator
  version: 2.0.0
- addonChannel: beta
  csvNameOverride: klusterlet-product
  image: quay.io/acm-d/klusterlet-operator-bundle:v2.0.1-11
  operator: klusterlet-operator
  version: 2.0.1
