bundles:
- addonChannel: beta
  image: quay.io/acm-d/acm-operator-bundle:v2.7.0-248
  dash: pre7
  operator: advanced-cluster-management
  version: 2.7.0
- addonChannel: beta
  image: quay.io/acm-d/mce-operator-bundle:v2.2.0-247
  dash: pre7
  operator: multicluster-engine
  parent: advanced-cluster-management
  version: 2.2.0
